name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge CDN Cache
        uses: egad13/purge-jsdelivr-cache@v1
        with:
          # This tells jsDelivr to clear the cache for the whole branch
          url: |
            https://cdn.jsdelivr.net/gh/SGolden58/svg@main/
