name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr
        run: |
          # This command tells jsDelivr to clear the cache for your main branch
          curl -i https://purge.jsdelivr.net/gh/SGolden58/svg@main/
