name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr CDN cache
        run: |
          curl -i -X GET "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/"
